#!/usr/bin/python3

from lib import parsers
from lib.defaults import defaults
from lib.compose_runner import run_compose_command

def main():
    settings = parsers.load_settings(defaults['settings'])
    run_compose_command(['down', '--rmi', 'all'])

main()

